# Generated by Django 3.1.3 on 2020-11-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('cuisine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='recipes.cuisines')),
                ('favorites', models.ManyToManyField(related_name='favorites', to='accounts.user_details')),
            ],
        ),
    ]
