# Generated by Django 3.1.3 on 2020-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201117_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisines',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
